import changes from cperl
===Config: fix compilation with c++===

error: a cast to a type other than an integral or enumeration type cannot
appear in a constant-expression. VUNDEF, ...

===Fix rurban email address===

use the generic cpan.org

===Config: gperf fixup===

detect size_t instead of int also, to convert the stringpool ptr to U16

===Config 6.23: fixup lookup size_t from gperf 3.1===

gperf 3.1 supports longer keys, but we prefer U32_MAX keys.
patch size_t back to unsigned int, as we use unsigned int all over.
See #286

Add --gperf /usr/local/bin/perf argument, to override PATH settings.
When gperf failed print the system error:
"No such file or directory"

bulk88 note: --gperf isn't used by cperl build process, it is a dev tool

===Config: support ext/Config/Config_xs.PL --regen===

to overwrite Config_xs.out.
To support reproducible builds with different gperf versions.

bulk88 note: always regen for cpan release since I need to make sure the
canned gperf hash is upto date

bulk88 specific change:
-fixed XSConfig.t to work with newer Test::More based off Test2